// app/components/home-component/plans.ts
export const plans = [
  {
    name: "Starter",
    tier: "starter",
    tagline: "Start Putting Structure Around Your Business",
    price: "₦99,900",
    altPrice: "$69",
    suffix: "/year",
    yearlyAmount: 99900,
    note: "For solo founders and early-stage businesses.",
    region: "global",
    features: [
      "Business bank account",
      "Business Plan Template",
      "Automatic Bookkeeping",
      "Invoice Tool",
      "Receipt Tool",
      "Online storefront",
      "Document Vault",
    ],
    cta: "Start Your Free Trial",
    featured: false,
    amount: 99900,
  },
  {
    name: "SME",
    tier: "sme",
    tagline: "Run Your Business Properly",
    price: "₦199,900",
    altPrice: "$139",
    suffix: "/year",
    yearlyAmount: 199900,
    note: "For growing small businesses with a small team.",
    region: "global",
    features: [
      "Business bank account",
      "Business Plan Template",
      "Automatic Bookkeeping",
      "Invoice Tool",
      "Receipt Tool",
      "International payments",
      "Online storefront",
      "Document Vault",
      "One Extra User",
    ],
    cta: "Start Your Free Trial",
    featured: true,
    amount: 199900,
    addons: [
      "Payroll",
      "HMO",
      "Tax Filing Support",
      "Virtual office/mailing address",
    ],
  },
  {
    name: "Enterprise",
    tier: "enterprise",
    tagline: "Full Business Finance System",
    price: "₦599,900",
    altPrice: "$419",
    suffix: "/year",
    yearlyAmount: 599900,
    note: "For organizations with teams and multiple operators.",
    region: "global",
    features: [
      "Business bank account",
      "Increased transaction limits",
      "Business Plan Template",
      "Automatic Bookkeeping",
      "Connect Your Bank Accounts",
      "Invoice Tool",
      "Receipt Tool",
      "International payments",
      "Online storefront",
      "Document Vault",
      "Three Extra Users",
      "Dedicated support team",
    ],
    cta: "Start Your Free Trial",
    featured: false,
    amount: 599900,
    addons: [
      "Payroll",
      "HMO",
      "Tax Filing Support",
      "Virtual office/mailing address",
    ],
  },
];