export const plans = [
  {
    name: "FREE",
    tier: "free",
    tagline: "Get a business bank account for free",
    price: "₦0",
    altPrice: "$0",
    suffix: "/month",
    note: "Business Account plan",
    region: "global",
    features: [
      "Business bank account at 0.2% per transaction",
      "Business account activation fee: N1000",
      "Payment links and payment APIs",
      "Available for Nigeria only",
    ],
    cta: "Start Free",
    featured: false,
    amount: 0,
  },
  {
    name: "STARTER",
    tier: "starter",
    tagline: "Become organized",
    price: "₦9,900",
    altPrice: "$8",
    suffix: "/month",
    yearlyPrice: "₦99,900/year",
    threeMonthPrice: "₦29,900/3 months",
    yearlyAmount: 99900,
    threeMonthAmount: 29900,
    note: "Get organized",
    region: "global",
    features: [
      "Everything in Free, plus:",
      "Business Plan Template",
      "Bookkeeping Tool",
      "Business bank account",
      "Invoice Tool",
      "Receipt Tool",
      "Document Vault",
    ],
    cta: "Go STARTER",
    featured: true,
    amount: 9900,
  },
  {
    name: "SME",
    tier: "sme",
    tagline: "Grow with clarity",
    price: "₦19,900",
    altPrice: "$15",
    suffix: "/month",
    yearlyPrice: "₦199,900/year",
    threeMonthPrice: "₦59,900/3 months",
    yearlyAmount: 199900,
    threeMonthAmount: 59900,
    note: "Grow with clarity",
    region: "global",
    features: [
      "Everything in Starter, plus:",
      "Tax tool",
      "Product webpage",
      "One Extra User",
      "Switch between Accounts",
      "Add-ons (additional fee): Payroll, HMO, Tax Filing Support",
    ],
    cta: "Go SME",
    featured: false,
    amount: 19900,
  },
  {
    name: "ENTERPRISE",
    tier: "enterprise",
    tagline: "Control team operations",
    price: "₦59,900",
    altPrice: "$43",
    suffix: "/month",
    yearlyPrice: "₦599,900/year",
    threeMonthPrice: "₦179,900/3 months",
    yearlyAmount: 599900,
    threeMonthAmount: 179900,
    note: "Control team operations",
    region: "global",
    features: [
      "Everything in SME, plus:",
      "Advanced Bookkeeping Tool",
      "Connected bank accounts",
      "Contract Tool",
      "Upload bank statements",
      "Downloadable financial statements",
      "2 Extra Users",
      "Add-ons (additional fee): Payroll, HMO, Tax Filing Support",
    ],
    cta: "Go ENTERPRISE",
    featured: false,
    amount: 59900,
  },
  {
    name: "CONSOLE",
    tier: "console",
    tagline: "Run a business with multiple outlets",
    price: "Custom Pricing",
    altPrice: "",
    suffix: "",
    note: "Custom Pricing for multiple outlets and teams",
    region: "global",
    features: [
      "Sub accounts - create multiple accounts for people and outlets",
      "Multi-users + signatories",
      "Request and Approval workflow",
      "Advanced finance dashboard",
      "Plus every other tool on Zidwell",
    ],
    cta: "Contact Sales",
    featured: false,
    amount: 0,
  },
];
