export const plans = [
  {
    name: "Free",
    tier: "free",
    tagline: "Start Managing Your Money",
    price: "₦0",
    altPrice: "$0",
    suffix: "/month",
    note: "For individuals and early-stage freelancers.",
    region: "global",
    features: [
      "Manual bookkeeping — Global",
      "Auto-bookkeeping (Wallet users, Nigeria)",
      "Payment Links & Sales pages (Nigeria)",
      "Free business bank account (Nigeria)",
      "Up to 5 invoices — Global",
      "Up to 5 receipts — Global",
      "Basic financial overview",
    ],
    cta: "Start Free",
    featured: false,
    amount: 0,
  },
  {
    name: "Solopreneur",
    tier: "solopreneur",
    tagline: "Get Organized",
    price: "₦4,900",
    altPrice: "$3.99",
    suffix: "/month",
    yearlyPrice: "₦49,000/year (save ₦9,800)",
    yearlyAmount: 49000,
    note: "For freelancers and solo business owners.",
    region: "global",
    features: [
      "Everything in Free, plus:",
      "Up to 10 invoices",
      "Unlimited receipts",
      "Branded invoices",
      "Better expense tracking",
      "Basic financial insights",
    ],
    cta: "Go Solopreneur",
    featured: false,
    amount: 4900,
  },
  {
    name: "SME",
    tier: "sme",
    tagline: "Run Your Business Properly",
    price: "₦29,900",
    altPrice: "$21.99",
    suffix: "/month",
    yearlyPrice: "₦299,000/year (save ₦59,800)",
    yearlyAmount: 299000,
    note: "For growing small businesses.",
    region: "global",
    features: [
      "Everything in Solopreneur, plus:",
      "Upload bank statements (PDF / Excel / CSV)",
      "Connect up to 3 bank accounts — Nigeria",
      "Auto-bookkeeping from connected accounts — Nigeria",
      "Unlimited invoices & receipts",
      "Vault — store financial documents safely",
      "Tax calculator",
      "Financial statements (view): P&L · Cashflow · Balance Sheet",
      "1 extra team member",
    ],
    cta: "Go SME",
    featured: true,
    amount: 29900,
  },
  {
    name: "Enterprise",
    tier: "enterprise",
    tagline: "Team Business Management",
    price: "₦100,000",
    altPrice: "$75",
    suffix: "/month",
    yearlyPrice: "₦1,000,000/year (save ₦200,000)",
    yearlyAmount: 1000000,
    note: "For teams that need structure.",
    region: "global",
    features: [
      "Everything in SME, plus:",
      "Multi-user access (full team)",
      "Role-based permissions",
      "Approvals for payments, invoices, receipts, transfers",
      "Connect up to 5 bank accounts — Nigeria",
      "Downloadable financial reports",
      "10 contracts",
      "Dedicated onboarding support",
    ],
    cta: "Go Enterprise",
    featured: false,
    amount: 100000,
  },
  {
    name: "Corporation",
    tier: "corporation",
    tagline: "Full Business Finance System",
    price: "₦300,000",
    altPrice: "$220",
    suffix: "/month",
    yearlyPrice: "₦3,000,000/year (save ₦600,000)",
    yearlyAmount: 3000000,
    note: "For large organizations and structured companies.",
    region: "global",
    features: [
      "Everything in Enterprise, plus:",
      "Unlimited contracts",
      "Department-based access (HR, Finance, Ops…)",
      "Connect unlimited bank accounts — Nigeria",
      "Simple payroll system",
      "Advanced financial reporting",
      "Custom financial structure setup",
      "Priority onboarding & dedicated account manager",
    ],
    cta: "Talk to Sales",
    featured: false,
    amount: 300000,
  },
];