// app/lib/bankFormats.ts

export interface BankFormat {
  name: string;
  patterns: RegExp[];
  dateFormat: string;
  dateRegex: RegExp;
  amountRegex: RegExp;
  descriptionRegex: RegExp;
  balanceRegex?: RegExp;
  referenceRegex?: RegExp;
  creditIndicators: string[];
  debitIndicators: string[];
  skipLines: number;
  headers: string[];
  color?: string;
  region: 'nigeria' | 'international' | 'global';
}

export const bankFormats: BankFormat[] = [
  // ============================================
  // NIGERIAN BANKS
  // ============================================
  {
    name: 'GTBank',
    patterns: [/GTBank/i, /Guaranty Trust Bank/i, /GTCO/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'INFLOW', 'RECEIVED', 'TRANSFER FROM'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT', 'TRANSFER TO', 'CHARGES'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#E85D3A',
    region: 'nigeria',
  },
  {
    name: 'Zenith Bank',
    patterns: [/Zenith Bank/i, /ZENITH/i],
    dateFormat: 'dd-MM-yyyy',
    dateRegex: /(\d{2}-\d{2}-\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#CC0000',
    region: 'nigeria',
  },
  {
    name: 'Access Bank',
    patterns: [/Access Bank/i, /Access/i],
    dateFormat: 'dd-MM-yyyy',
    dateRegex: /(\d{2}-\d{2}-\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#0066B3',
    region: 'nigeria',
  },
  {
    name: 'UBA',
    patterns: [/UBA/i, /United Bank for Africa/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#D81F26',
    region: 'nigeria',
  },
  {
    name: 'First Bank',
    patterns: [/First Bank/i, /FirstBank/i, /FBN/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#003B7A',
    region: 'nigeria',
  },
  {
    name: 'Opay',
    patterns: [/Opay/i, /OPAY/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'RECEIVED', 'DEPOSIT', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#00B074',
    region: 'nigeria',
  },
  {
    name: 'PalmPay',
    patterns: [/PalmPay/i, /PALMPAY/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'RECEIVED', 'DEPOSIT', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#7A37D6',
    region: 'nigeria',
  },
  {
    name: 'Kuda Bank',
    patterns: [/Kuda/i, /KUDA/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'RECEIVED', 'DEPOSIT', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#40196D',
    region: 'nigeria',
  },
  {
    name: 'Stanbic IBTC',
    patterns: [/Stanbic/i, /Stanbic IBTC/i, /IBTC/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#0047A0',
    region: 'nigeria',
  },
  {
    name: 'FCMB',
    patterns: [/FCMB/i, /First City Monument Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#005DA0',
    region: 'nigeria',
  },
  {
    name: 'Sterling Bank',
    patterns: [/Sterling/i, /Sterling Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#ED1C24',
    region: 'nigeria',
  },
  {
    name: 'Union Bank',
    patterns: [/Union Bank/i, /UNION/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#003F6C',
    region: 'nigeria',
  },
  {
    name: 'Wema Bank',
    patterns: [/Wema/i, /Wema Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#003C71',
    region: 'nigeria',
  },
  {
    name: 'Providus Bank',
    patterns: [/Providus/i, /Providus Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#1A3C5E',
    region: 'nigeria',
  },
  {
    name: 'Jaiz Bank',
    patterns: [/Jaiz/i, /Jaiz Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#1E7B3B',
    region: 'nigeria',
  },
  {
    name: 'Taj Bank',
    patterns: [/Taj/i, /Taj Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#2E7D32',
    region: 'nigeria',
  },
  {
    name: 'SunTrust Bank',
    patterns: [/SunTrust/i, /SunTrust Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#F7931E',
    region: 'nigeria',
  },
  {
    name: 'Globus Bank',
    patterns: [/Globus/i, /Globus Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#0055A4',
    region: 'nigeria',
  },

  // ============================================
  // INTERNATIONAL BANKS
  // ============================================
  {
    name: 'Standard Chartered',
    patterns: [/Standard Chartered/i, /SCB/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#0A1E3F',
    region: 'international',
  },
  {
    name: 'Citibank',
    patterns: [/Citibank/i, /Citi/i],
    dateFormat: 'MM/dd/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#004B87',
    region: 'international',
  },
  {
    name: 'HSBC',
    patterns: [/HSBC/i, /HONG KONG/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#DB0011',
    region: 'international',
  },
  {
    name: 'Barclays',
    patterns: [/Barclays/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#00AE9D',
    region: 'international',
  },
  {
    name: 'Chase',
    patterns: [/Chase/i, /JPMorgan/i],
    dateFormat: 'MM/dd/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#1D2A47',
    region: 'international',
  },
  {
    name: 'Bank of America',
    patterns: [/Bank of America/i, /BOA/i],
    dateFormat: 'MM/dd/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#004B87',
    region: 'international',
  },
  {
    name: 'Wells Fargo',
    patterns: [/Wells Fargo/i],
    dateFormat: 'MM/dd/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#CD140A',
    region: 'international',
  },
  {
    name: 'TD Bank',
    patterns: [/TD Bank/i, /Toronto Dominion/i],
    dateFormat: 'MM/dd/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#00853E',
    region: 'international',
  },
  {
    name: 'Royal Bank of Canada',
    patterns: [/RBC/i, /Royal Bank of Canada/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#003366',
    region: 'international',
  },
  {
    name: 'Deutsche Bank',
    patterns: [/Deutsche Bank/i, /Deutsche/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#003D8C',
    region: 'international',
  },
  {
    name: 'BNP Paribas',
    patterns: [/BNP Paribas/i, /BNP/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#009E60',
    region: 'international',
  },
  {
    name: 'Santander',
    patterns: [/Santander/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#EC0000',
    region: 'international',
  },
  {
    name: 'Lloyds Bank',
    patterns: [/Lloyds/i, /Lloyds Bank/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#0072B0',
    region: 'international',
  },
  {
    name: 'NatWest',
    patterns: [/NatWest/i, /National Westminster/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT'],
    skipLines: 1,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#009BCC',
    region: 'international',
  },

  // ============================================
  // GENERIC / FALLBACK
  // ============================================
  {
    name: 'Generic CSV',
    patterns: [/\.csv$/i, /\.xlsx$/i, /\.xls$/i],
    dateFormat: 'dd/MM/yyyy',
    dateRegex: /(\d{2}\/\d{2}\/\d{4}|\d{4}-\d{2}-\d{2})/,
    amountRegex: /([\d,]+\.\d{2})/,
    descriptionRegex: /^[^,]+,/,
    creditIndicators: ['CREDIT', 'DEPOSIT', 'RECEIVED', 'INFLOW', '+'],
    debitIndicators: ['DEBIT', 'WITHDRAWAL', 'OUTFLOW', 'PAYMENT', '-'],
    skipLines: 0,
    headers: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    color: '#6B7280',
    region: 'global',
  },
];

// Helper function to detect bank format from text
export function detectBankFormat(text: string): BankFormat | null {
  const firstLines = text.split('\n').slice(0, 10).join('\n');
  
  for (const format of bankFormats) {
    if (format.patterns.some(pattern => pattern.test(firstLines))) {
      return format;
    }
  }
  return bankFormats.find(f => f.name === 'Generic CSV') || null;
}

// Helper function to get bank format by name
export function getBankFormatByName(name: string): BankFormat | undefined {
  return bankFormats.find(f => f.name.toLowerCase() === name.toLowerCase());
}

// Helper function to get banks by region
export function getBankFormatsByRegion(region: 'nigeria' | 'international' | 'global'): BankFormat[] {
  return bankFormats.filter(f => f.region === region || f.region === 'global');
}

// Helper function to get all bank names
export function getBankNames(): string[] {
  return bankFormats.map(f => f.name);
}

// Helper function to get Nigerian bank names
export function getNigerianBankNames(): string[] {
  return bankFormats.filter(f => f.region === 'nigeria').map(f => f.name);
}

// Helper function to get international bank names
export function getInternationalBankNames(): string[] {
  return bankFormats.filter(f => f.region === 'international').map(f => f.name);
}