// app/lib/subscription-features.ts
export const SUBSCRIPTION_FEATURES = {
  free: {
    invoices_total: { value: '5', limit: 5 },
    receipts_total: { value: '5', limit: 5 },
    contracts_total: { value: '0', limit: 0 },
    bookkeeping_trial_days: { value: '14', limit: 14 },
    tax_calculator_trial_days: { value: '14', limit: 14 },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'basic', limit: null },
    manual_bookkeeping: { value: 'true', limit: null },
    auto_bookkeeping_nigeria: { value: 'true', limit: null },
    payment_links_nigeria: { value: 'true', limit: null },
    business_bank_account_nigeria: { value: 'true', limit: null },
    basic_financial_overview: { value: 'true', limit: null },
  },
  solopreneur: {
    invoices_total: { value: '10', limit: 10 },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: '0', limit: 0 },
    bookkeeping_trial_days: { value: '14', limit: 14 },
    tax_calculator_trial_days: { value: '14', limit: 14 },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'whatsapp', limit: null },
    manual_bookkeeping: { value: 'true', limit: null },
    auto_bookkeeping_nigeria: { value: 'true', limit: null },
    payment_links_nigeria: { value: 'true', limit: null },
    business_bank_account_nigeria: { value: 'true', limit: null },
    branded_invoices: { value: 'true', limit: null },
    expense_tracking: { value: 'true', limit: null },
    basic_financial_insights: { value: 'true', limit: null },
  },
  sme: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: '1', limit: 1 },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'whatsapp', limit: null },
    bank_statement_upload: { value: 'true', limit: null },
    connect_bank_accounts: { value: '3', limit: 3 },
    vault: { value: 'true', limit: null },
    financial_statements: { value: 'true', limit: null },
    team_members: { value: '1', limit: 1 },
  },
  enterprise: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: '10', limit: 10 },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'priority', limit: null },
    multi_user_access: { value: 'true', limit: null },
    role_permissions: { value: 'true', limit: null },
    approval_system: { value: 'true', limit: null },
    connect_bank_accounts: { value: '5', limit: 5 },
    downloadable_reports: { value: 'true', limit: null },
    dedicated_onboarding: { value: 'true', limit: null },
  },
  corporation: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: 'unlimited', limit: null },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '0', limit: null },
    support_type: { value: 'dedicated_account_manager', limit: null },
    department_access: { value: 'true', limit: null },
    unlimited_bank_accounts: { value: 'true', limit: null },
    payroll_system: { value: 'true', limit: null },
    advanced_reporting: { value: 'true', limit: null },
    custom_financial_structure: { value: 'true', limit: null },
    priority_onboarding: { value: 'true', limit: null },
    dedicated_account_manager: { value: 'true', limit: null },
  },
};

export const TIER_HIERARCHY = ['free', 'solopreneur', 'sme', 'enterprise', 'corporation'];

export const TIER_DISPLAY_NAMES = {
  free: 'Free',
  solopreneur: 'Solopreneur',
  sme: 'SME',
  enterprise: 'Enterprise',
  corporation: 'Corporation',
};

export const TIER_PRICING = {
  free: { monthly: 0, yearly: 0 },
  solopreneur: { monthly: 4900, yearly: 49000 },
  sme: { monthly: 29900, yearly: 299000 },
  enterprise: { monthly: 100000, yearly: 1000000 },
  corporation: { monthly: 300000, yearly: 3000000 },
};