// app/lib/subscription-features.ts
export const SUBSCRIPTION_FEATURES = {
  free: {
    invoices_total: { value: '5', limit: 5 },
    receipts_total: { value: '5', limit: 5 },
    contracts_total: { value: '0', limit: 0 },
    bookkeeping_trial_days: { value: '14', limit: 14 },
    tax_calculator_trial_days: { value: '14', limit: 14 },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'basic', limit: null },
    manual_bookkeeping: { value: 'true', limit: null },
    auto_bookkeeping_nigeria: { value: 'true', limit: null },
    payment_links_nigeria: { value: 'true', limit: null },
    business_bank_account_nigeria: { value: 'true', limit: null },
    basic_financial_overview: { value: 'true', limit: null },
  },
  starter: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: '0', limit: 0 },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'whatsapp', limit: null },
    vault: { value: 'true', limit: null },
    team_members: { value: '1', limit: 1 },
  },
  sme: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: '1', limit: 1 },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'whatsapp', limit: null },
    bank_statement_upload: { value: 'true', limit: null },
    connect_bank_accounts: { value: '3', limit: 3 },
    vault: { value: 'true', limit: null },
    financial_statements: { value: 'true', limit: null },
    team_members: { value: '1', limit: 1 },
    product_webpage: { value: 'true', limit: null },
  },
  enterprise: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: '10', limit: 10 },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '50', limit: null },
    support_type: { value: 'priority', limit: null },
    multi_user_access: { value: 'true', limit: null },
    role_permissions: { value: 'true', limit: null },
    approval_system: { value: 'true', limit: null },
    connect_bank_accounts: { value: '5', limit: 5 },
    downloadable_reports: { value: 'true', limit: null },
    dedicated_onboarding: { value: 'true', limit: null },
    product_webpage: { value: 'true', limit: null },
    team_members: { value: '2', limit: 2 },
  },
  console: {
    invoices_total: { value: 'unlimited', limit: null },
    receipts_total: { value: 'unlimited', limit: null },
    contracts_total: { value: 'unlimited', limit: null },
    bookkeeping_access: { value: 'true', limit: null },
    tax_calculator: { value: 'true', limit: null },
    transfer_fee: { value: '0', limit: null },
    support_type: { value: 'dedicated_account_manager', limit: null },
    department_access: { value: 'true', limit: null },
    unlimited_bank_accounts: { value: 'true', limit: null },
    payroll_system: { value: 'true', limit: null },
    advanced_reporting: { value: 'true', limit: null },
    custom_financial_structure: { value: 'true', limit: null },
    priority_onboarding: { value: 'true', limit: null },
    dedicated_account_manager: { value: 'true', limit: null },
    sub_accounts: { value: 'true', limit: null },
    multi_users_signatories: { value: 'true', limit: null },
    request_approval_workflow: { value: 'true', limit: null },
    advanced_finance_dashboard: { value: 'true', limit: null },
  },
};

export const TIER_HIERARCHY = ['free', 'starter', 'sme', 'enterprise', 'console'];

export const TIER_DISPLAY_NAMES = {
  free: 'FREE',
  starter: 'STARTER',
  sme: 'SME',
  enterprise: 'ENTERPRISE',
  console: 'CONSOLE',
};

export const TIER_PRICING = {
  free: { monthly: 0, yearly: 0, threeMonth: 0 },
  starter: { monthly: 9900, yearly: 99900, threeMonth: 29900 },
  sme: { monthly: 19900, yearly: 199900, threeMonth: 59900 },
  enterprise: { monthly: 59900, yearly: 599900, threeMonth: 179900 },
  console: { monthly: 0, yearly: 0, threeMonth: 0 },
};