// lib/subscription-features.ts
export const SUBSCRIPTION_FEATURES = {
  free: {
    business_bank_account: { value: "true", limit: null },
    business_plan_template: { value: "true", limit: null },
    automatic_bookkeeping: { value: "true", limit: null },
    invoices_total: { value: "5", limit: 5 },
    receipts_total: { value: "5", limit: 5 },
    online_storefront: { value: "true", limit: null },
    document_vault: { value: "true", limit: null },
    basic_financial_overview: { value: "true", limit: null },
    transfer_fee: { value: "50", limit: null },
    support_type: { value: "basic", limit: null },
  },
  starter: {
    business_bank_account: { value: "true", limit: null },
    business_plan_template: { value: "true", limit: null },
    automatic_bookkeeping: { value: "true", limit: null },
    invoices_total: { value: "unlimited", limit: null },
    receipts_total: { value: "unlimited", limit: null },
    online_storefront: { value: "true", limit: null },
    document_vault: { value: "true", limit: null },
    transfer_fee: { value: "50", limit: null },
    support_type: { value: "whatsapp", limit: null },
    team_members: { value: "0", limit: 0 },
  },
  sme: {
    business_bank_account: { value: "true", limit: null },
    business_plan_template: { value: "true", limit: null },
    automatic_bookkeeping: { value: "true", limit: null },
    invoices_total: { value: "unlimited", limit: null },
    receipts_total: { value: "unlimited", limit: null },
    online_storefront: { value: "true", limit: null },
    document_vault: { value: "true", limit: null },
    international_payments: { value: "true", limit: null },
    transfer_fee: { value: "50", limit: null },
    support_type: { value: "whatsapp", limit: null },
    team_members: { value: "1", limit: 1 },
    addon_payroll: { value: "false", limit: null },
    addon_hmo: { value: "false", limit: null },
    addon_tax_filing: { value: "false", limit: null },
    addon_virtual_office: { value: "false", limit: null },
  },
  enterprise: {
    business_bank_account: { value: "true", limit: null },
    business_plan_template: { value: "true", limit: null },
    automatic_bookkeeping: { value: "true", limit: null },
    invoices_total: { value: "unlimited", limit: null },
    receipts_total: { value: "unlimited", limit: null },
    online_storefront: { value: "true", limit: null },
    document_vault: { value: "true", limit: null },
    international_payments: { value: "true", limit: null },
    connect_bank_accounts: { value: "true", limit: null },
    increased_transaction_limits: { value: "true", limit: null },
    transfer_fee: { value: "50", limit: null },
    support_type: { value: "priority", limit: null },
    team_members: { value: "3", limit: 3 },
    dedicated_support_team: { value: "true", limit: null },
    addon_payroll: { value: "false", limit: null },
    addon_hmo: { value: "false", limit: null },
    addon_tax_filing: { value: "false", limit: null },
    addon_virtual_office: { value: "false", limit: null },
  },
  console: {
    // Custom pricing tier — same features as enterprise plus more
    business_bank_account: { value: "true", limit: null },
    business_plan_template: { value: "true", limit: null },
    automatic_bookkeeping: { value: "true", limit: null },
    invoices_total: { value: "unlimited", limit: null },
    receipts_total: { value: "unlimited", limit: null },
    online_storefront: { value: "true", limit: null },
    document_vault: { value: "true", limit: null },
    international_payments: { value: "true", limit: null },
    connect_bank_accounts: { value: "true", limit: null },
    increased_transaction_limits: { value: "true", limit: null },
    transfer_fee: { value: "0", limit: null },
    support_type: { value: "dedicated_account_manager", limit: null },
    team_members: { value: "unlimited", limit: null },
    dedicated_support_team: { value: "true", limit: null },
    sub_accounts: { value: "true", limit: null },
    roles_permissions: { value: "true", limit: null },
    approvals: { value: "true", limit: null },
    addon_payroll: { value: "true", limit: null },
    addon_hmo: { value: "true", limit: null },
    addon_tax_filing: { value: "true", limit: null },
    addon_virtual_office: { value: "true", limit: null },
  },
};

export const TIER_HIERARCHY = [
  "free",
  "starter",
  "sme",
  "enterprise",
  "console",
];

export const TIER_DISPLAY_NAMES = {
  free: "Free",
  starter: "Starter",
  sme: "SME",
  enterprise: "Enterprise",
  console: "Console",
};

export const TIER_PRICING = {
  free: { yearly: 0 },
  starter: { yearly: 99900 },
  sme: { yearly: 199900 },
  enterprise: { yearly: 599900 },
  console: { yearly: 0 }, // custom pricing
};